import argparse

def parse_args():
    parser = argparse.ArgumentParser(description='parameters')
    parser.add_argument('--max_len', type=int, default=10)
    parser.add_argument('--epoch', type=int, default=25)
    parser.add_argument('--eval_per_epoch', type=int, default=2)
    parser.add_argument('--lr', type=float, default=1e-03)
    parser.add_argument('--encoder', type=str, default='bert-base-uncased')
    parser.add_argument('--weight_decay', type=float, default=0)
    parser.add_argument('--dropout', type=float, default=0.1)
    parser.add_argument('--seed', type=int, default=213214)
    parser.add_argument('--local_rank', type=int, default=-1)
    parser.add_argument('--data_dir', type=str, default='data')
    parser.add_argument('--node_info_path', type=str, default='data/node2id.tsv')
    parser.add_argument('--train_file_path', type=str, default='data/train.tsv')
    parser.add_argument('--dev_file_path', type=str, default='data/dev.tsv')
    parser.add_argument('--user_list', type=str, default='data/user_list.tsv')
    parser.add_argument('--domain_list', type=str, default='data/domain_list.tsv')
    parser.add_argument('--pretrain_user', type=str, default='data/pretrained_userembeddings_0919.npy')
    parser.add_argument('--pretrain_domain', type=str, default='data/pretrained_domainembeddings_0919.npy')
    # parser.add_argument('--pretrain_user', type=str, default=None)
    # parser.add_argument('--pretrain_domain', type=str, default=None)
    parser.add_argument('--reprocessed', type=str, default='false')
    parser.add_argument('--processed_train_node2examples', type=str, default='data/train_node2examples.pkl')
    #parser.add_argument('--processed_train_edge2examples', type=str, default='data_0810/graph_info/train_edge2examples.pkl')
    # parser.add_argument('--pretrain_user', type=str, default=None)
    # parser.add_argument('--pretrain_domain', type=str, default=None)
    parser.add_argument('--train_batch_size', type=int, default=512)
    parser.add_argument('--eval_batch_size', type=int, default=512)
    parser.add_argument('--output_dir', type=str, default='new_pass_outputs/output1')
    parser.add_argument('--load_from_checkpoint', type=str, default="new_pass_outputs/output1/run_31/pytorch_model.22795.bin")
    #parser.add_argument('--load_from_qk', type=str, default='qk_outputs/run_1/pytorch_model.15008.bin')
    parser.add_argument('--load_from_qk', type=str, default=None)
    
    return parser.parse_args()